#dataset에 들어가는 열 index
# FOOD_ID = 0
# FOOD_INDEX = 1
# ENERGY_INDEX = 3
# PROTEIN_INDEX = 4
# FAT_INDEX = 5
# CHO_INDEX = 6
# DISH_TYPE_INDEX = 
# MAIN_INGREDIENTS_INDEX = 8
# MAIN_INGREDIENTS_2_INDEX = 9
# CHEWING_STAGE = 10

#CHO_INDEX = 5
#CONSISTENCY_INDEX = 6
#DISH_TYPE_INDEX = 7
#COLOR_INDEX = 8
#MAIN_INGREDIENTS_INDEX = 9
#MAIN_INGREDIENTS_2_INDEX = 10
#MEAL_GROUP_INDEX = 11


# #dataset에 들어가는 열 index
FOOD_ID = 0
FOOD_INDEX = "meal_name"
ENERGY_INDEX = "energy"
PROTEIN_INDEX = "protein"
FAT_INDEX = "fat"
CHO_INDEX = "cho"
MAIN_INGREDIENTS_INDEX = 8
MAIN_INGREDIENTS_2_INDEX = 9
CHEWING_STAGE = 10
DISH_TYPE_INDEX = "dish_type"
PREFERENCE = "preference"
